server:
  port: 8080
  tomcat:
    access-log-enabled: true

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mariadb://localhost:3306/jwt_security_db
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect




